### ISSUE TITLE
Unexpected non-0 padding byte `1`

### ISSUE THREAD

**Issue by warusadura** [dbus2/zbus#1303]
Hey @zeenix 

I have [this](https://github.com/warusadura/prompter/blob/master/src/main.rs) small project (plan to integrate this into new gnome-keyring daemon) where I'm trying to test gnome-keyring prompter [interface](https://gitlab.gnome.org/GNOME/gcr/-/blob/main/gcr/org.gnome.keyring.Prompter.xml). Currently I'm defining `properties` - type: `a{sv}` as `HashMap<&str, OwnedValue>`. Everything works with this approach.

But, when tried to define `properties` as a struct I'm getting `Unexpected non-0 padding byte '1'` error.

Diff:
```rust
diff --git a/src/main.rs b/src/main.rs
index 1bec693..f499f89 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -2,7 +2,7 @@ use std::collections::HashMap;
 
 use zbus::{
     fdo, interface, proxy,
-    zvariant::{OwnedObjectPath, OwnedValue, Value},
+    zvariant::{OwnedObjectPath, OwnedValue, Value, SerializeDict, DeserializeDict, Type},
     Connection,
 };
 
@@ -18,13 +18,26 @@ pub trait Prompter {
         &self,
         callback: OwnedObjectPath,
         type_: &str,
-        properties: HashMap<&str, OwnedValue>,
+        properties: Properties,
         exchange: &str,
     ) -> Result<(), fdo::Error>;
 
     fn stop_prompting(&self, callback: OwnedObjectPath) -> Result<(), fdo::Error>;
 }
 
+#[derive(Debug, DeserializeDict, SerializeDict, Type)]
+#[zvariant(signature = "dict")]
+pub struct Properties {
+    #[zvariant(rename = "continue-label")]
+    continue_label: Option<String>,
+    description: Option<String>,
+    message: Option<String>,
+    #[zvariant(rename = "caller-window")]
+    caller_window: Option<String>,
+    #[zvariant(rename = "cancel-label")]
+    cancel_label: Option<String>,
+}
+
 pub struct PrompterCallback {
     path: OwnedObjectPath,
 }
@@ -34,7 +47,7 @@ impl PrompterCallback {
     pub async fn prompt_ready(
         &self,
         reply: &str,
-        _properties: HashMap<&str, OwnedValue>,
+        _properties: Properties,
         exchange: &str,
         #[zbus(connection)] connection: &zbus::Connection,
     ) {
@@ -57,6 +70,14 @@ impl PrompterCallback {
         properties.insert("caller-window", Value::new("").try_to_owned().unwrap());
         properties.insert("cancel-label", Value::new("Cancel").try_to_owned().unwrap());
 
+        let p = Properties {
+            continue_label: Some("Lock".to_owned()),
+            description: Some("Confirm locking 'login' Keyring".to_owned()),
+            message: Some("Lock Keyring".to_owned()),
+            caller_window: Some(String::new()),
+            cancel_label: Some("Cancel".to_owned()),
+        };
+
         let path = self.path.clone();
         let connection = connection.clone();
         let exchange = exchange.to_owned();
@@ -64,7 +85,7 @@ impl PrompterCallback {
         tokio::spawn(async move {
             let prompter = PrompterProxy::new(&connection).await.unwrap();
             prompter
-                .perform_prompt(path, "confirm", properties, &exchange)
+                .perform_prompt(path, "confirm", p, &exchange)
                 .await
                 .unwrap();
         });
```

Based on [this](https://gitlab.freedesktop.org/dbus/zbus/-/issues/82) similar error, I have double checked Properties struct field names. Everything is good. So, I really have no idea what's causing this error and how to fix this :)

**Comment by zeenix** [comment]
> But, when tried to define `properties` as a struct I'm getting `Unexpected non-0 padding byte '1'` error.

This is very strange. This really should work. We've a bunch of tests for these derive macros. The error you're getting suggests that something is getting (de)serialized with the wrong type.

> Based on [this](https://gitlab.freedesktop.org/dbus/zbus/-/issues/82) similar error, I have double checked Properties struct field names. Everything is good. So, I really have no idea what's causing this error and how to fix this :)

That issue is super old and was fixed long time ago, so very unlikely to be relevant anyway but good that you checked. I'm quite puzzled myself here.

**Comment by warusadura** [comment]
Thanks for the reply, understood.

**Comment by zeenix** [comment]
I wonder if this is a duplicate of #856. 🤔 Could you see if you're sending the correct types for all values from the other side? Also try and setting all fields (if you weren't already).

**Comment by warusadura** [comment]
Thanks for the prompt responses.

Yeah, I think this may be related to that issue. I followed the following suggestion mentioned in that issue
> If this is changed to Ok(visitor.visit_seq(value_de).unwrap()), it outputs:

and I get,

```
called `Result::unwrap()` on an `Err` value: Message("invalid value: string \"v\", expected the value signature")
```

And yes, I tried setting all fields and I'm still getting this error.

**Comment by bilelmoussaoui** [comment]
What happens if you have only one field in the Properties struct, for example `description`, does it work?

**Comment by warusadura** [comment]
> What happens if you have only one field in the Properties struct, for example `description`, does it work?

No, it doesn't work. I'm still getting the `Unexpected non-0 padding byte 1` error. It's pretty weird, I tried all the properties one by one, one at a time and still failed. The only time I didn't get this error is when I'm using a `HashMap` and when the Properties struct has no fields :)

**Comment by zeenix** [comment]
> > What happens if you have only one field in the Properties struct, for example `description`, does it work?
> 
> No, it doesn't work. I'm still getting the `Unexpected non-0 padding byte 1` error. It's pretty weird, I tried all the properties one by one, one at a time and still failed. The only time I didn't get this error is when I'm using a `HashMap` and when the Properties struct has no fields :)

Are you sure? I reduced the code to a minimal reproducer and I can reproduce the issue that the encoding is different but [when I remove all but one field](https://github.com/zeenix/prompter/commit/ca768ee538e0da2b718bb8da41b868d182089c94), the encoding is identical:

```
❯ cargo r
   Compiling prompter v0.1.0 (/tmp/prompter)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.85s
     Running `target/debug/prompter`
encoded bytes len: 41
encoded struct bytes len: 41  
❯ 
```

**Comment by bilelmoussaoui** [comment]
heh sounds fun! I get the same results as you
```
user@fedora ~/P/prompter (master)> cargo r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/prompter`
encoded bytes len: 73
encoded struct bytes len: 74

thread 'main' panicked at src/main.rs:36:5:
assertion `left == right` failed
  left: [66, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 99, 111, 110, 116, 105, 110, 117, 101, 45, 108, 97, 98, 101, 108, 0, 1, 115, 0, 0, 0, 4, 0, 0, 0, 76, 111, 99, 107, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 0, 1, 115, 0, 0, 1, 0, 0, 0, 120, 0]
 right: [65, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 0, 1, 115, 0, 0, 1, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 99, 111, 110, 116, 105, 110, 117, 101, 45, 108, 97, 98, 101, 108, 0, 1, 115, 0, 0, 0, 4, 0, 0, 0, 76, 111, 99, 107, 0]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
user@fedora ~/P/prompter (master) [101]> cargo r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/prompter`
encoded bytes len: 74
encoded struct bytes len: 74
user@fedora ~/P/prompter (master)> cargo r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/prompter`
encoded bytes len: 74
encoded struct bytes len: 74
user@fedora ~/P/prompter (master)> cargo r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/prompter`
encoded bytes len: 73
encoded struct bytes len: 74

thread 'main' panicked at src/main.rs:36:5:
assertion `left == right` failed
  left: [66, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 99, 111, 110, 116, 105, 110, 117, 101, 45, 108, 97, 98, 101, 108, 0, 1, 115, 0, 0, 0, 4, 0, 0, 0, 76, 111, 99, 107, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 0, 1, 115, 0, 0, 1, 0, 0, 0, 120, 0]
 right: [65, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 0, 1, 115, 0, 0, 1, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 99, 111, 110, 116, 105, 110, 117, 101, 45, 108, 97, 98, 101, 108, 0, 1, 115, 0, 0, 0, 4, 0, 0, 0, 76, 111, 99, 107, 0]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
user@fedora ~/P/prompter (master) [101]> cargo r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/prompter`
encoded bytes len: 73
encoded struct bytes len: 74

thread 'main' panicked at src/main.rs:36:5:
assertion `left == right` failed
  left: [66, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 99, 111, 110, 116, 105, 110, 117, 101, 45, 108, 97, 98, 101, 108, 0, 1, 115, 0, 0, 0, 4, 0, 0, 0, 76, 111, 99, 107, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 0, 1, 115, 0, 0, 1, 0, 0, 0, 120, 0]
 right: [65, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 0, 1, 115, 0, 0, 1, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 99, 111, 110, 116, 105, 110, 117, 101, 45, 108, 97, 98, 101, 108, 0, 1, 115, 0, 0, 0, 4, 0, 0, 0, 76, 111, 99, 107, 0]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
user@fedora ~/P/prompter (master) [101]> 
```

**Comment by zeenix** [comment]
Oh, nm! I forgot to take into account the fact that a `HashMap` is not ordered so you can't rely on the iteration order and that changes the encoding. Comparing the bytes was a bad idea. :)

**Comment by zeenix** [comment]
Ok ok, I gutted zbus and got a dump of the message body that we fail to deserialize and [made a minimal reproducer](https://github.com/zeenix/prompter/blob/0e4a7b3fdb4c4f023733bcb73fa5881b911fd390/src/main.rs) using that. We already know that it's the deserialization that fails so this has to be in DeserializeDict.

**Comment by zeenix** [comment]
Alright I've managed to [narrowed down the problem to `DeserializeValue`](https://github.com/zeenix/prompter/commit/400213061e82a5cef5f323d3c023aa496df9c089). I'll either fix this or just deprecate these types and change the macro to not use them.

**Comment by zeenix** [comment]
> Alright I've managed to [narrowed down the problem to `DeserializeValue`](https://github.com/zeenix/prompter/commit/400213061e82a5cef5f323d3c023aa496df9c089). I'll either fix this or just deprecate these types and change the macro to not use them.

Oh, this keeps getting more and more interesting. Turns out that the encoded data has an extra variant wrapper (i-e `Value::Value(Value::Str)` instead of `Value::Str`). From what I can tell looking at the code, the only diff is that `Value` deserialization is somehow able to handle this case but `DeserializeValue` isn't (and I don't think it should).

@bilelmoussaoui So I think is likely a bug in gcr.

**Comment by bilelmoussaoui** [comment]
cc @warusadura  ^

**Comment by zeenix** [comment]
Yeah, this is a bug in gcr: [It wraps the value in an extra variant](https://gitlab.gnome.org/GNOME/gcr/-/blob/main/gcr/gcr-system-prompter.c?ref_type=heads#L469). 🤦

**Comment by warusadura** [comment]
Thanks @zeenix and @bilelmoussaoui . Will get this fixed in gcr :)

**Comment by warusadura** [comment]
Will do, thanks!

**Comment by zeenix** [comment]
> Please be careful as this is an API break, very likely. Ping me on the PR.

I'd be very surprised if this is the case though. gcr happily accepts and parses the dict we send it and also I don't see a reason there would be a need for a double-wrapping here.

But you never know. 🤷 Please put me in CC too.
